<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-AV2ODUL9" ignored="0" name="placeValidation" tests="1" failures="1" timestamp="03 Jul 2020 10:27:31 GMT" time="0.51" errors="0">
  <testcase name="Login" time="0.367" classname="com.automation.runners.placeRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Actuals did not match with expected:: expected [20] but found [200]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Actuals did not match with expected:: expected [20] but found [200]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at com.automation.runners.placeRunner.Login(placeRunner.java:59)
Caused by: java.lang.AssertionError: Actuals did not match with expected:: expected [20] but found [200]
	at com.automation.stepdefinitions.StepDefination.the_API_call_got_success_with_status_code(StepDefination.java:60)
	at âœ½.Then the API call got success with status code 200(src/test/java/com/automation/features/placeValidations.feature:5)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- placeValidation -->
